packages:
  - test/*
  - docs
  - reader
catalog:
  '@element-plus/icons-vue': ^2.1.0
  '@vitejs/plugin-vue': ^5.2.1
  dexie: ^3.2.3
  element-plus: ^2.3.1
  epub: ^1.2.1
  file-saver: ^2.0.5
  pinia: 2.0.23
  pinia-plugin-persistedstate: ^3.2.0
  sass: ^1.61.0
  spark-md5: ^3.0.2
  unplugin-auto-import: ^0.16.6
  unplugin-vue-components: ^0.24.1
  vue-easy-lightbox: ^1.19.0
  vue-router: ^4.2.5
  vue-reader: latest
  vite: ^7.1.12
